version: '3.3'
services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: '312project'
      MYSQL_USER: 'user'              
      MYSQL_PASSWORD: 'password'
    ports:
     - '3306'
  app:
    build: .
    environment:
      WAIT_HOSTS: mysql:3306
      DB_USERNAME: 'user'
      DB_PASSWORD: 'password'
    ports:
      - '8080:8000'




